### ISSUE TITLE
Im871A

### ISSUE THREAD

**Issue by lzxtct** [rscada/libmbus#107]
Hi,
I am a student, and I am working on the project about Mbus. I used the broad from IMST(im871) to transfer the meter reading to the im871 USB adapter connect with Raspberry Pi. I am totally begineer in this area. Is any advice to my project? Your reply is really helpful to me.
Thank you so much.

**Comment by lategoodbye** [comment]
AFAIK the Im871A is a wireless M-Bus device, but libmbus doesn't support wireless M-Bus yet. So we can't help you.
