### ISSUE TITLE
Libtoolize and automake trouble

### ISSUE THREAD

**Issue by mitmacher** [rscada/libmbus#112]
Hi,
I'm having trouble installing the library on Raspberry Pi 3. 

I start with downloading the zip and unzip it, cd to the directory and then 

`autoheader && aclocal && libtoolize --ltdl --copy --force && automake --add-missing --copy && autoconf`

After this it says:
---
Consider using 'AC_CONFIG_AUX_DIR([libtdl/config])' in configure.ac.

automake: warnings are treated as errors
/usr/share/automake-1.14/am/ltllibrary.am: warning: 'libmbus.la': linking libtool libraries using a non-POSIX
/usr/share/automake-1.14/am/ltllibrary.am: archiver requires 'AM_PROG_AR' in 'configure.ac'
mbus/Makefile.am16: while processing Libtool library 'libmbus.la'

---
Anyone can help me with these errors?

Im thankful for any help.

Greetings,

Max

**Comment by lategoodbye** [comment]
@mitmacher 

Does the patch from @jasp fix your issue?
https://github.com/keepfocus/libmbus/commit/111bbb71d4ef3eed8ecc36bf5353da16a401828c.patch

**Comment by mitmacher** [comment]
Worked. Thank you very much.
