### ISSUE TITLE
can any one tell me how to build windows support dll from this source or .o(object files )

### ISSUE THREAD

**Issue by ncmsilva** [rscada/libmbus#117]

**Comment by lategoodbye** [comment]
Sorry, this library wasn't written for Windows. Maybe you could try it with [Cygwin](https://www.cygwin.com/).

**Comment by Apollon77** [comment]
I made some progress and got it working on Windows also without Cygwin ... Maybe have a look at my current working branch:

https://github.com/Apollon77/libmbus/tree/build-windows

I use this branch in my new nodejs-native module ... Any feedback or support and working with me to finalize it would be great

Ingo
