### ISSUE TITLE
Interfacing to Aidon 6525 3-phase electric meter

### ISSUE THREAD

**Issue by sritam2** [rscada/libmbus#144]
Hi All,
I read the HAN interface description manual of the electric meter I am using. It is mentioned that only the TX-pin and the ground pin of the HAN port(of the electric meter) was exposed for external interface. It means that the meter will only transmit M-Bus data packets to the external world and does not want to receive any M-Bus data packets from external world. Does this mean that the electric meter used by me is a M-Bus master device and I need to implement a M-Bus slave device externally using a micro-controller or linux based embedded board(for eg: Raspberry Pi)?

I have attached the HAN interface document of the electric meter I am using. In section 2.2 in page 4 it is mentioned that 2 pins(TX and GND) are used for HAN.
[Aidon-HAN-Interface-Description-v10A-ID-34331.pdf](https://github.com/rscada/libmbus/files/2834555/Aidon-HAN-Interface-Description-v10A-ID-34331.pdf)

Please help me with your valuable comments.

Thanks and Regards,
Sritam Paltasingh.

**Comment by lategoodbye** [comment]
This meter doesn't speak M-Bus. It provides a DLMS/COSEM interface via RS232.
