### ISSUE TITLE
Error decoding Wmbus Telegram

### ISSUE THREAD

**Issue by 0xcore** [rscada/libmbus#146]
Error decoding Wmbus Oms telegram, from Danfoss Sonometer 30 heat meter.

mbus_parse_hex -n danfoss_frame.hex

**mbus_parse: Invalid M-Bus frame start.**

danfoss_frame.hex:
4e 44 d3 10 13 17 05 00 50 04 7a af 00 30 05 2f 2f 0c 06 00 00 00 00 04 6d 03 2c 34 25 0c 13 21 33 00 00 8c 40 13 00 00 00 00 8c 80 40 13 00 00 00 00 0b 3b 13 00 00 0b 2d 00 00 00 2f 2f 2f

Can someone help?

Thanks!

**Comment by lategoodbye** [comment]
Sorry, but libmbus doesn't support wireless m-bus.

**Comment by 0xcore** [comment]
Ok. Thanks!
