### ISSUE TITLE
10^9 is Giga not Terra

### ISSUE THREAD

**Issue by lvogt** [rscada/libmbus#147]
https://github.com/rscada/libmbus/blob/2dc3daaf7080cb77640e6caee3154585b8196a37/mbus/mbus-protocol.c#L1826

10^9 is Giga.

On a side note: I think outputting the data with this mix of metric prefixes and "number multipliers" is not really a good idea...

**Comment by Apollon77** [comment]
@lvogt is this an issue in ioBroker? Then I can fix it in my fork for node-mbus and also deliver as PR for here .. ?!

**Comment by lvogt** [comment]
My parsing code knows of this bug and treats T as 10^9...
However, I think this is more of a theoretical problem as I don't think there are many meters which output values in this range...

**Comment by Apollon77** [comment]
Ok, then I wait for an official merge or repsonse and we update later

**Comment by lategoodbye** [comment]
Sorry, i'm busy with BCM2835 stuff. But any PR is welcome.
