### ISSUE TITLE
libmbus does not work with level converter which echo the request

### ISSUE THREAD

**Issue by luetgendorf** [rscada/libmbus#24]
I've a rs232 to mbus converter which echo the request sent from the lib. Is there any simple solution to that?

**Comment by AhmyOhlin** [comment]
Iam working with L-MBUS20  of loytec and i get this issue everytime:
[/usr/share/mbus/libmbus/bin $ sudo ./mbus-serial-scan -d -b 2400 /dev/ttyUSB0
Scanning primary addresses:
0 [2018-01-16 16:05:53] SEND (005): 10 40 00 40 16
1 [2018-01-16 16:05:53] SEND (005): 10 40 01 41 16
2 [2018-01-16 16:05:53] SEND (005): 10 40 02 42 16
3 [2018-01-16 16:05:53] SEND (005): 10 40 03 43 16
4 [2018-01-16 16:05:54] SEND (005): 10 40 04 44 16
[2018-01-16 16:05:54] RECV (001): FD
Collision at address 4
5 [2018-01-16 16:05:55] SEND (005): 10 40 05 45 16
6 [2018-01-16 16:05:55] SEND (005): 10 40 06 46 16
[2018-01-16 16:05:55] RECV (001): FE
Collision at address 6
7 [2018-01-16 16:05:56] SEND (005): 10 40 07 47 16
8 [2018-01-16 16:05:56] SEND (005): 10 40 08 48 16
[2018-01-16 16:05:56] RECV (001): FC
Collision at address 8](url)
