### ISSUE TITLE
Raspberry Pi - libmbus.so.0

### ISSUE THREAD

**Issue by stenebo** [rscada/libmbus#78]
Hello, I've compiled libmbus in raspbian with kernel 3.12.28.
Now I get the following error when I run mbus-tcp-scan or mbus-serial-scan:

mbus-tcp-scan: error while loading shared libraries: libmbus.so.0: cannot open shared object file: No such file or directory

I've searched the file and it exist in /usr/local/lib/libmbus.so.0
So I added it to PATH with: `export PATH=$PATH:/usr/local/lib`
But still same error, any ideas?
/Per

**Comment by kkro** [comment]
Running still fine on Debian 12 64-bit but this commet is so important.

And:

_autoconf
./configure
make__

is not enough, you need this:

_libtoolize --force
aclocal
autoheader
automake --force-missing --add-missing
autoconf
./configure
make_
